# Generated by Django 3.1.2 on 2020-10-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Acrylic Painting', 'Acrylic Painting'), ('Oil Painting', 'Oil Painting'), ('Water Color Painting', 'Water Color Painting')], default='Acrylic Painting', max_length=200, null=True)),
                ('price', models.FloatField(null=True, verbose_name='$')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
