# Generated by Django 3.1.2 on 2020-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201019_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_imgae',
            field=models.ImageField(default='profile.png', null=True, upload_to=''),
        ),
    ]
