# Generated by Django 3.1.2 on 2020-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_imgae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_imgae',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product.jpg', null=True, upload_to=''),
        ),
    ]
