# Generated by Django 3.1.6 on 2021-02-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0002_auto_20210207_2127'),
        ('product', '0006_auto_20201023_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_accounts.seller'),
        ),
    ]
