# Generated by Django 3.1.6 on 2021-02-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0002_auto_20210207_2127'),
        ('product', '0007_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_accounts.seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
