# Generated by Django 3.1.2 on 2020-10-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_product',
            old_name='cart_item',
            new_name='cartitem',
        ),
    ]
