# Generated by Django 3.1.6 on 2021-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
