# Generated by Django 3.1.6 on 2021-02-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0003_auto_20210220_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
