# Generated by Django 3.1.6 on 2021-02-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0004_auto_20210220_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='about',
        ),
    ]
