# Generated by Django 3.1.6 on 2021-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_accounts', '0005_remove_seller_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
